apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "9042"
      port: 9042
      targetPort: 9042
  selector:
    io.kompose.service: cassandra
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: CASSANDRA_PASSWORD
              value: cassandra
            - name: CASSANDRA_PASSWORD_SEEDER
              value: "yes"
            - name: CASSANDRA_SEEDS
              value: cassandra
          image: docker.io/bitnami/cassandra:4.0
          name: cassandra
          ports:
            - containerPort: 7000
            - containerPort: 9042
          resources: {}
          volumeMounts:
            - mountPath: /bitnami
              name: cassandra-cassandra-data
      restartPolicy: Always
      volumes:
        - name: cassandra-cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-cassandra-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra-cassandra-data
  name: cassandra-cassandra-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
