kind: ConfigMap
apiVersion: v1
metadata:
  name: CM
  namespace: ildidemo
data:
  key: ildidemo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  multiprojekt
  namespace: ildidemo
  labels:
    app:  multiprojekt
spec:
  selector:
    matchLabels:
      app: multiprojekt
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  multiprojekt
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  multiprojekt
        image:  pontosrepo.ildi.app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: multiprojekt
              key: DB_HOST
        ports:
        - containerPort:  8080
          name:  multiprojekt
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always